server:
  port: ${SERVER_PORT:8080}

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

spring:
  profiles:
    active:
      - ${PROFILE_ACTIVE:DEV}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  metrics:
    enable:
      jvm: true
    tags:
      application: app-localiza-api
  prometheus:
    metrics:
      export:
        enabled: true