spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${POSTGRES_DB}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

  # Email Settings

  mail:
    host: smtp.gmail.com
    port: 587
    username: 7a91e21577624f37a2dd@gmail.com
    password: lxuyvwtqtrhrtmpu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

    # Email Settings

# Spring Doc
springdoc:
  packages-to-scan:
    - com.luanpaiva.localizaapi.adapter.input.api
  paths-to-match:
    - /v1/**
# Spring Doc