info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

spring:
  profiles:
    active:
      - ${PROFILE_ACTIVE:DEV}
server:
  port: ${SERVER_PORT:9000}