server:
  port: ${SERVER_PORT:8080}

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

spring:
  profiles:
    active:
      - ${PROFILE_ACTIVE:LOCAL}

  # Email Settings
  mail:
    host: smtp.gmail.com
    port: 587
    username: "7a91e21577624f37a2dd@gmail.com"
    password: lxuyvwtqtrhrtmpu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Email Settings

localiza.email.remetente: Localiza API <7a91e21577624f37a2dd@gmail.com>

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  metrics:
    enable:
      jvm: true
    tags:
      application: app-localiza-api
  prometheus:
    metrics:
      export:
        enabled: true