spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

# Spring Doc
springdoc:
  packages-to-scan:
    - com.luanpaiva.localizaapi.adapter.input.api
  paths-to-match:
    - /v1/**
# Spring Doc