spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

# Spring Doc

springdoc:
  packages-to-scan:
    - com.luanpaiva.localizaapi.adapter.input.api
  paths-to-match:
    - /v1/**

# Spring Doc