global:
  scrape_interval: 5s
scrape_configs:
  - job_name: prometheus-api
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - prometheus-api:9090
  - job_name: localiza-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - localiza-api:8080